apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: catalogue-

labels:
  - pairs:
      app.kubernetes.io/name: tutors-catalogue
      app.kubernetes.io/component: catalogue
    includeSelectors: true
    includeTemplates: true

images:
  - name: tutors-app
    newName: quay.io/tutors-sdk/tutors-catalogue
    newTag: "16.2.2"
    digest: sha256:f6cdb7f6adaba1d227e2cf62260ec2fe7064c58114666774331da3530bf52187

patches:
  - target:
      kind: ConfigMap
      name: tutors-app-config
    patch: |
      - op: replace
        path: /data/ORIGIN
        value: "https://catalogue.tutors.dev"
