apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tutors-app
  labels:
    app.kubernetes.io/part-of: tutors
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tutors-app
