apiVersion: v1
kind: Service
metadata:
  name: tutors-app
  labels:
    app.kubernetes.io/part-of: tutors
spec:
  selector:
    app.kubernetes.io/name: tutors-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
