packages:
  - "packages/jsr/*"
  - "packages/svelte/*"
  - "packages/svelte/utils/*"
  - "apps/*"
  - "services/party"
allowBuilds:
  esbuild: true
  msw: true
  workerd: true
minimumReleaseAgeExclude:
  - '@skeletonlabs/skeleton-common@5.0.1'
  - '@skeletonlabs/skeleton-svelte@5.0.1'
  - '@skeletonlabs/skeleton@5.0.1'
  - dompurify@3.4.14
  - happy-dom@20.11.6
  - vite@8.2.2
overrides:
  cookie: ">=0.7.0 <1.0.0"
