/**
 * `@tutors/scorm` — lets Tutors act as the LMS for an imported SCORM package.
 *
 * The export direction (a Tutors course packaged for someone else's LMS) is generated by
 * `@tutors/tutors-gen-lib`; this package is the other half, hosting third-party content.
 */

export { createScorm12Api, createScorm2004Api, installScormApi, ScormRuntime } from "./api.ts";
export type { Scorm12Api, Scorm2004Api } from "./api.ts";
export { CmiModel, SCORM_ERROR } from "./model.ts";
export { resolveScormAsset, SCORM_ASSET_ROUTE, scormAssetUrl } from "./proxy.ts";
export { startScormSession } from "./session.ts";
export type { ScormSession, ScormSessionOptions } from "./session.ts";
export { createLocalScormStore, createScormStore } from "./store.ts";
export { formatDuration, parseDuration } from "./time.ts";
export type { ScormApiOptions, ScormStore, ScormSummary, ScormVersion } from "./types.ts";
