apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: time-

labels:
  - pairs:
      app.kubernetes.io/name: tutors-time
      app.kubernetes.io/component: time
    includeSelectors: true

images:
  - name: tutors-app
    newName: registry.example.com/tutors/time
    newTag: latest

patches:
  - target:
      kind: ConfigMap
      name: tutors-app-config
    patch: |
      - op: replace
        path: /data/origin
        value: "https://time.tutors.dev"
